### ISSUE TITLE
ESLint - no extraneous dependencies 

### ISSUE THREAD

**Issue by BernardA** [jagaapple/next-secure-headers#29]
# 💩 Bug Report
## A summary of the bug
ESLint is throwing an error on:

`const { createSecureHeaders } = require('next-secure-headers');`

> 'next-secure-headers' should be listed in the project's dependencies, not devDependencies.eslintimport/no-extraneous-dependencies

**I was in fact wondering why should this be a development dependency given that the directives should, of course, be included in production.** 

## Current behavior

This is next.config.js

       const { createSecureHeaders } = require('next-secure-headers');

     module.exports = {
         async headers() {
            return [{ source: '/(.*)', headers: createSecureHeaders() }];
        },
     };

### To Reproduce

Install using `$ npm install -D next-secure-headers`

Per your documentation, it should be installed with the `-D` option, unless :
 

>   ❗️ For withSecureHeaders . If you want to use withSecureHeaders , you have to install without -D option (i.e., installing as dependencies not devDependencies )

.

## Expected behavior
No warnings from ESLint

## Environment
- This project version(s): `v2.0.0`
- Nextjs version: 9.5.3
- Nodejs version: `v12.16.0`
- OS: `macOS 10.15.6`

## Additional context
Add any other context about the problem here, or a screenshot if applicable.

---

- [ ] I've tried to find similar issues
- [ ] I would like to work on a fix 💪🏻

**Comment by jagaapple** [comment]
@BernardA 
Are you using any servers through `getInitialProps` or `getServerSideProps` ?
You can install as `devDependencies` if you publish pages as static pages including SSG. In this case, `createSecureHeaders` will be loaded in only buid steps. Otherwise, you have to install as (production) dependencies even if you're using `createSecureHeaders` .

**Comment by BernardA** [comment]
Thanks. I am not using any own servers as far as I know. I develop with `npm run dev` and then deploy it to vercel.com. 
That would mean that I will just have to silence the ESLint warning, I believe.

**Comment by jagaapple** [comment]
`next dev` or `vercel dev` commands will render any contents as server-side rendering even if a page does not use `getInitialProps` such as, so I think the warnings has been occurred 🤔 

In any case, there is a need to correct readme.

**Comment by jagaapple** [comment]
I understand why this is happened now (because I've never used this rule), and I think it's better to use `eslint-disable` special comments where you import next-secure-headers to disable the rule. The rule prohibits importing packages in devDependencies anywhere, but next-secure-headers is imported in only build-phase if you don't run any servers, so you don't need to install as `dependencies` .

If I miunderstand about that, please mention to me.
